<template>
  <div class="box" id="mentions-header">
    <span class="h1">
      <router-link to="/" title="MonSociogram.me"
        ><img src="assets/img/logo.svg" width="50"
      /></router-link>
      <span> MonSociogram<span class="small">.me</span> </span>
    </span>
  </div>

  <div id="mentions-legales" class="box">
    <h2>Mentions légales</h2>

    <br />

    <h2>L’éditeur</h2>
    Création, développement, maintenance, contact...
    <ul>
      <li class="bold">Pierre GIRARDOT</li>
      <li>Mail : ketluts [at] ketluts [point] net</li>
    </ul>

    <br />

    <h2>L’hébergeur</h2>
    <ul>
      <li class="bold">
        OVH <br />2 rue Kellermann <br />59100 ROUBAIX – France
        <br />
      </li>
      <li>
        Pour contacter cet hébergeur, rendez-vous à l’adresse
        <a href="http://www.ovh.com/fr/support/"
          >http://www.ovh.com/fr/support/</a
        >
      </li>
    </ul>

    <br />

    <h2>Vie privée / Cookies</h2>
    C'est très simple, MonSociogram.me n'utilise aucun traceur à visée
    publicitaire. Seul l'identifiant de la session est stocké dans votre
    navigateur afin de faciliter la reconnexion à votre compte.
    <br />
    Vous disposez d’un droit d’accès, de modification, de rectification et de
    suppression des données qui vous concernent. Ces données ne seront pas
    partagées, elles restent internes au site.

    <br />
    <br />

    <h2>Bibliothèques utilisées</h2>

    <ul>
      <li><a href="https://getbootstrap.com/">Bootstrap</a></li>
      <li><a href="https://datatables.net/">Datatables</a></li>
      <li>
        Font generated by
        <a href="http://www.flaticon.com">flaticon.com</a> under
        <a href="http://creativecommons.org/licenses/by/3.0/">CC BY</a>. The
        authors are: <a href="http://www.freepik.com">Freepik</a>.
      </li>
      <li><a href="https://handlebarsjs.com/">HandlebarsJS</a></li>

      <li><a href="https://www.highcharts.com/">Highcharts</a></li>
      <li><a href="https://icons.getbootstrap.com/">Icons</a></li>
      <li><a href="https://jdenticon.com">Jdenticon</a></li>
      <li><a href="https://jquery.com/">Jquery</a></li>
      <li><a href="https://jqueryui.com/">Jquery UI</a></li>
      <li><a href="https://momentjs.com/">MomentJS</a></li>

      <li><a href=" https://mustache.github.io/">Mustache</a></li>

      <li><a href="http://phpqrcode.sourceforge.net/">PHPQRCode</a></li>
      <li><a href="https://opencollective.com/select2">Select2</a></li>
      <li><a href="https://sweetalert2.github.io/">SweetAlert2</a></li>
    </ul>
  </div>
</template>

<script>
// @ is an alias to /src
export default {
  name: "Mentions",
  components: {},
};
</script>
